### PR TITLE
fix(ons-splitter): Fixes #1717.

### LINKED ISSUE #1717: Second splitter menu does not work
__Environment__ 

```
[Core]
    Onsen UI 2.0.4

[Framework]
    None

[Framework binding]
    None

[Additional libraries]
    None

[Platform]
    Desktop - Linux

[Browser]
    Desktop - Chrome 53.0.2785.116
    Desktop - Chromium 53.0.2785.143
    Desktop - Firefox 50.0
```

__Encountered problem__

I have 2 splitter menus on left and right sides.
One is collapsed and swipeable, the other is not.
But the swipe does not work properly: the content is not grayed out, and the menu does not collapse if I tap outside.

__How to reproduce__

https://codepen.io/anon/pen/eBGgvJ

### PR DESCRIPTION
**Pull request by misterjunio**
@asial-matagawa Think I found the problem of #1717. The mask was being hidden in CSS if there was one `ons-splitter-side` sibling in `split` mode, which was wrong in case there was another `collapse`-mode `ons-splitter-side`. Instead I'm hiding the mask after the content is ready only if *all* `ons-splitters` are in `split` mode. Please take a look when you can 🙂

### CODE REVIEW

File: core/src/elements/ons-splitter-mask.js [hunk 1]
```diff
@@ -17,11 +17,20 @@ limitations under the License.
...
 import BaseElement from '../ons/base-element';
 import util from '../ons/util';
+import contentReady from '../ons/content-ready';
 
 export default class SplitterMaskElement extends BaseElement {
 
   init() {
     this._boundOnClick = this._onClick.bind(this);
+    contentReady(this, () => {
+      console.log(this.parentNode._sides);
```
Comment (frandiox) [inline core/src/elements/ons-splitter-mask.js]: :scream:

Comment (misterjunio) [inline core/src/elements/ons-splitter-mask.js]: Sumimasen ❌

**Comment by asial-matagawa** [comment]
@misterjunio 
I have checked your commits and I think it is fine. Thank you!

**Comment by misterjunio** [comment]
@asial-matagawa great, I'll merge i then 👍
