### PR TITLE
Carousel fix

### LINKED ISSUE #2065: Angular1 | Carousel issue: Carousel does not function properly when using a border
```
[Core]
  onsenui 2.3.3
  
[Framework]
  angular1 1.5.5

[Framework binding]
 angular1-onsenui latest

[Platform]
  Desktop - Windows 10 64-bit

[Browser]
  Desktop - Chrome 58.0.3029.110 on Windows 10 64-bit
```

__Encountered problem__
I am having issues implementing a carousel in my web app with ng-repeat. Every time I click the next button, the new carousel item is slightly to the left and off the screen. This effect stacks.

Here are screenshots:

Setting item-width and centered does not fix the problem.

**EDIT:**
When I click the demo link on this post, I experience the problem I describe. After I refresh it, it works as expected.

__How to reproduce__
  Click the arrows to scroll through the carousel.

  
  [__Demo link__](https://tutorial.onsen.io/?issue)

  

- __HTML__

```html
<ons-page ng-controller="CarouselController">
  <ons-toolbar>
    <div class="left">
      <ons-toolbar-button ng-click="carousel.prev()">
        <ons-icon icon="md-chevron-left"></ons-icon>
      </ons-toolbar-button>
    </div>
    <div class="center">Carousel</div>
    <div class="right">
      <ons-toolbar-button ng-click="carousel.next()">
        <ons-icon icon="md-chevron-right"></ons-icon>
      </ons-toolbar-button>
    </div>
  </ons-toolbar>

<ons-carousel var="carousel" style="margin: 0 auto; width: 250px !important; height: 100px !important; border-radius: 10px !important; border-color: #337ab7 !important; border-width: 2px !important; border-style: solid !important;" swipeable auto-scroll overscrollable>
    <ons-carousel-item ng-repeat="number in numbersArray">
      <p>
        {{number}}
      </p>
    </ons-carousel-item>tem>
  </ons-carousel>
</ons-page>
```

- __JS__

```javascript
ons.bootstrap()
  .controller('CarouselController', ['$scope', function($scope) {
    
    $scope.numbersArray = [11111, 22222, 33333, 44444, 55555, 66666, 77777, 88888, 99999, 00000];
  }]);
```

### PR DESCRIPTION
**Pull request by misterjunio**
@asial-matagawa @frandiox this PR fixes #2065. We weren't taking the carousel border into account when calculating the item size.

### CODE REVIEW

File: core/src/elements/ons-carousel.js [hunk 1]
```diff
@@ -33,7 +33,8 @@ const VerticalModeTrait = {
 
   _getElementSize: function() {
     if (!this._currentElementSize) {
-      this._currentElementSize = this.getBoundingClientRect().height;
+      var styling = getComputedStyle(this, null);
+      this._currentElementSize = this.getBoundingClientRect().height - parseInt(styling.getPropertyValue('border-right-width')) - parseInt(styling.getPropertyValue('border-left-width'));
```
Comment (asial-matagawa) [inline core/src/elements/ons-carousel.js]: I guess `border-right-width` should be `border-top-height` or something?

Comment (misterjunio) [inline core/src/elements/ons-carousel.js]: oooops, you're partially right, it should be `border-top-width` and `border-bottom-width`

**Comment by frandiox** [comment]
@misterjunio Thanks!
