### PR TITLE
fix(vue): make options.animation work for v-ons-splitter-side

### LINKED ISSUE #2394: Vue | Splitter issue: :options="{animation: 'reveal'}" is not working
__Environment__

  
```
[Core]
  onsenui latest
  
[Framework]
  vue 2.4.1

[Framework binding]
 vue-onsenui latest

[Platform]
  Desktop - OS X 10.12.6 64-bit

[Browser]
  Desktop - Chrome 65.0.3325.181 on OS X 10.12.6 64-bit
```

__Encountered problem__
  

The [document](https://onsen.io/v2/api/vue/v-ons-splitter-side.html) of `v-ons-splitter-side` says  
>options.animation | String | Specify the animation. Use one of overlay, push, reveal or default.Optional.

but `:options="{animation: 'reveal'}"` does not take effect.

As a workaround, `animation="reveal"` works (this is directly using the `animation` in Custom Elements layer).

__How to reproduce__
Add `:options="{animation: 'reveal'}"` into `<v-ons-splitter>` tag.
  

  
  [__Demo link__](https://onsen.io/playground/?issue)

  

- __HTML__

```html
<template id="main">
  <v-ons-splitter>
    <v-ons-splitter-side
      swipeable width="150px" collapse="" side="left"
      :open.sync="openSide"
      :options="{animation: 'reveal'}"
    >
      <v-ons-page>
        <v-ons-list>
          <v-ons-list-item v-for="page in pages"
            tappable modifier="chevron"
            @click="currentPage = page; openSide = false"
          >
            <div class="center">{{ page }}</div>
          </v-ons-list-item>
        </v-ons-list>
      </v-ons-page>
    </v-ons-splitter-side>

    <v-ons-splitter-content>
      <component :is="currentPage" :toggle-menu="() => openSide = !openSide"></component>
    </v-ons-splitter-content>
  </v-ons-splitter>
</template>

<template id="home">
  <v-ons-page>
    <custom-toolbar title="Home" :action="toggleMenu"></custom-toolbar>
    <p style="text-align: center">
      Welcome home.
    </p>
  </v-ons-page>
</template>

<template id="news">
  <v-ons-page>
    <custom-toolbar title="News" :action="toggleMenu"></custom-toolbar>
    <p style="text-align: center">
      Some news here.
    </p>
  </v-ons-page>
</template>

<template id="settings">
  <v-ons-page>
    <custom-toolbar title="Settings" :action="toggleMenu"></custom-toolbar>
    <p style="text-align: center">
      Change the settings.
    </p>
  </v-ons-page>
</template>

<template id="toolbar">
  <v-ons-toolbar>
    <div class="left">
      <v-ons-toolbar-button @click="action">
        <v-ons-icon icon="ion-navicon, material:md-menu"></v-ons-icon>
      </v-ons-toolbar-button>
    </div>
    <div class="center">{{ title }}</div>
  </v-ons-toolbar>
</template>

<div id="app"></div>
```

- __JS__

```javascript
const customToolbar = {
  template: '#toolbar',
  props: ['title', 'action']
};

const homePage = {
  template: '#home',
  props: ['toggleMenu'],
  components: { customToolbar }
};

const newsPage = {
  template: '#news',
  props: ['toggleMenu'],
  components: { customToolbar }
};

const settingsPage = {
  template: '#settings',
  props: ['toggleMenu'],
  components: { customToolbar }
};

new Vue({
  el: '#app',
  template: '#main',
  data() {
    return {
      currentPage: 'home',
      pages: ['home', 'news', 'settings'],
      openSide: false
    };
  },
  components: {
    home: homePage,
    news: newsPage,
    settings: settingsPage,
  }
});
```

### PR DESCRIPTION
**Pull request by emccorson**
Fixes #2394.

### CODE REVIEW

File: core/src/elements/ons-splitter-side.js [hunk 1]
```diff
@@ -629,6 +629,8 @@ export default class SplitterSideElement extends BaseElement {
     const unlock = this._lock.lock();
     this._state = CHANGING_STATE;
 
+    options.animation && this._updateAnimation(options.animation);
```
Comment (asialgearoid) [inline core/src/elements/ons-splitter-side.js]: I'm not a fan of this shorthand. It can easily be read as a mistake if someone doesn't totally understand how `&&` works. I'd prefer a simple `if` statement.

Comment (emccorson) [reply core/src/elements/ons-splitter-side.js]: Thanks, I've made the change. This shorthand is used all over the code so if we're not going to use it, I think we should either add it to the style guide in CONTRIBUTORS.md or to eslint.

Comment (asialgearoid) [reply core/src/elements/ons-splitter-side.js]: If we can add it to the eslint file, that would be great. This code all gets put through babel and minified, so saving space is not a concern :)
